"""Alembic environment — async SQLAlchemy support."""
import asyncio
import os
import ssl
import sys
from pathlib import Path
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine
from dotenv import load_dotenv

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

load_dotenv(Path(__file__).resolve().parents[2] / ".env")

# Override URL from environment (priority: DATABASE_URL > DATABASE_URL_SYNC > alembic.ini)
db_url = os.getenv("DATABASE_URL") or os.getenv("DATABASE_URL_SYNC")
if not db_url:
    db_url = config.get_main_option("sqlalchemy.url")

# Ensure URL uses asyncpg for async migrations
if db_url:
    if "psycopg2" in db_url:
        db_url = db_url.replace("postgresql+psycopg2", "postgresql+asyncpg")
    elif "postgresql://" in db_url and "+" not in db_url:
        db_url = db_url.replace("postgresql://", "postgresql+asyncpg://")
    
    # Remove sslmode from URL — we'll handle SSL explicitly
    if "sslmode=" in db_url:
        db_url = db_url.split("?")[0]

config.set_main_option("sqlalchemy.url", db_url)

# Phase 2: target_metadata now points at the real ORM models (src/db/models.py)
# so `alembic revision --autogenerate` produces a real diff instead of an
# empty migration. Migrations 001-003 were hand-written before this existed;
# 004 onward can be autogenerated (and should still be reviewed by hand —
# autogenerate does not detect RLS policies, CHECK constraints expressed via
# op.execute(), or the resolve_api_key_tenant() function, all of which stay
# hand-written regardless).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.db.models import Base  # noqa: E402

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations asynchronously with SSL support for Aiven."""
    db_url = config.get_main_option("sqlalchemy.url")
    
    # Determine if we need SSL
    needs_ssl = "aivencloud.com" in db_url
    
    # Build connect_args with SSL context
    connect_args = {}
    if needs_ssl:
        ssl_context = ssl.create_default_context()
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE
        # Pass SSL as a parameter that asyncpg will use directly
        connect_args["ssl"] = ssl_context
    
    # Create async engine
    engine = create_async_engine(
        db_url,
        poolclass=pool.NullPool,
        echo=False,
        connect_args=connect_args,
    )
    
    # Connect and run migrations
    async with engine.connect() as connection:
        await connection.run_sync(do_run_migrations)
    
    await engine.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
