"""
PatientVectorHub — SQLAlchemy ORM models.

Phase 2: Database Foundation, complete.

These models are the single source of truth for `alembic revision
--autogenerate` going forward (see migrations/env.py — target_metadata is
now Base.metadata instead of None). Migrations 001-003 created the first
three tables (tenants, users, patients) by hand with raw `op.create_table`;
004_add_core_tables.py adds the remaining five (documents, ingestion_jobs,
audit_logs, api_keys, query_logs) and this file's ORM classes now describe
all eight so future migrations can be autogenerated instead of hand-written.

Column-level enums are intentionally plain `sa.String` + a CHECK constraint
(added in the migration) rather than native Postgres ENUM types. This
matches the existing style in 002_create_seed_tables.py (tenants.plan,
users.role are plain strings) and avoids the ALTER TYPE ... ADD VALUE
ordering headaches Postgres enums bring later. Application-level validation
happens via the Literal/Enum types in schemas/*.py.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


# ── Root table — NOT tenant-scoped, no RLS (it defines tenants themselves) ──
class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    namespace: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    plan: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


# ── Tenant-scoped tables — all carry FORCE ROW LEVEL SECURITY (see migrations
#    003_enable_rls.py and 004_add_core_tables.py). Every query against these
#    must go through db.session.get_tenant_session(), which sets
#    app.tenant_id via set_config() before any statement runs. ──
class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = _uuid_pk()
    email: Mapped[str] = mapped_column(String(320), nullable=False, unique=True)
    keycloak_subject: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    role: Mapped[str] = mapped_column(String(64), nullable=False)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False
    )
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    last_login: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class Patient(Base):
    __tablename__ = "patients"

    id: Mapped[uuid.UUID] = _uuid_pk()
    mrn: Mapped[str] = mapped_column(String(255), nullable=False)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False
    )
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    documents: Mapped[list["Document"]] = relationship(back_populates="patient")


class IngestionJob(Base):
    __tablename__ = "ingestion_jobs"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    # queued | running | completed | failed | cancelled
    status: Mapped[str] = mapped_column(String(32), nullable=False, server_default="queued")
    # s3_batch | kafka_stream | api_push  (s3_batch also covers R2 — S3-compatible API, see ADR-009)
    source_type: Mapped[str] = mapped_column(String(32), nullable=False)
    source_config: Mapped[dict] = mapped_column(JSONB, nullable=False, server_default="{}")
    doc_count_total: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default="0")
    doc_count_processed: Mapped[int] = mapped_column(
        BigInteger, nullable=False, server_default="0"
    )
    doc_count_failed: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default="0")
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error_message: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    documents: Mapped[list["Document"]] = relationship(back_populates="ingestion_job")


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[uuid.UUID] = _uuid_pk()
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("patients.id"), nullable=False
    )
    # clinical_note | lab_result | imaging_report | discharge_summary | prescription
    document_type: Mapped[str] = mapped_column(String(32), nullable=False)
    source_path: Mapped[str] = mapped_column(Text, nullable=False)
    ingestion_job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("ingestion_jobs.id")
    )
    # pending | processing | completed | failed
    embedding_status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default="pending"
    )
    chunk_count: Mapped[int | None] = mapped_column(Integer)
    # e.g. "text-embedding-3-large" per ADR-009 (OpenAI, not self-hosted clinical-bert)
    model_version: Mapped[str | None] = mapped_column(String(128))
    vector_store: Mapped[str] = mapped_column(String(32), nullable=False, server_default="weaviate")
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False
    )
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    patient: Mapped["Patient"] = relationship(back_populates="documents")
    ingestion_job: Mapped["IngestionJob | None"] = relationship(back_populates="documents")


class ApiKey(Base):
    __tablename__ = "api_keys"

    id: Mapped[uuid.UUID] = _uuid_pk()
    key_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)  # SHA256 hex
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    scopes: Mapped[list[str]] = mapped_column(ARRAY(String), nullable=False, server_default="{}")
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    is_revoked: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class AuditLog(Base):
    """Append-only. See migration 004 for why this uses per-command
    policies (SELECT + INSERT only) instead of the single
    `WITH CHECK (FALSE)` policy shown in the original design docs —
    that form would have silently blocked INSERT too, not just
    UPDATE/DELETE. No ORM-level update/delete path is exposed for this
    model; crud.py only ever calls session.add() for it.
    """

    __tablename__ = "audit_logs"

    id: Mapped[uuid.UUID] = _uuid_pk()
    user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"))
    api_key_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("api_keys.id")
    )
    # document_query | document_ingest | phi_reveal | api_key_create |
    # api_key_revoke | user_login | settings_change | data_export
    action: Mapped[str] = mapped_column(String(32), nullable=False)
    patient_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    ip_address: Mapped[str | None] = mapped_column(String(64))
    request_id: Mapped[str | None] = mapped_column(String(64))
    status_code: Mapped[int | None] = mapped_column(Integer)
    audit_metadata: Mapped[dict] = mapped_column(
        "metadata", JSONB, nullable=False, server_default="{}"
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class QueryLog(Base):
    __tablename__ = "query_logs"

    id: Mapped[uuid.UUID] = _uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"))
    # SHA256 of query_text — never the raw text, PHI-free by construction
    query_text_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    result_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    model_version: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
